######################################################################################
# Linode plugin
######################################################################################

plugins:
  linode:
    executor: central_deployment_agent
    source: https://github.com/cloudify-cosmo/cloudify-linode-plugin/archive/master.zip


node_types:
  cloudify.linode.nodes.Linode:
    derived_from: cloudify.nodes.Compute
    properties:
      use_external_resource:
        description: >
          Indicates whether the resource exists of if Cloudify should create the resource.
        type: boolean
        default: false
      linode_id:
        description: >
          Whether external or created by the manager, Linodes will be associated with an ID
          assigned by Linode.
        type: interger
        default: -1
      linode_label:
        description: >
          A label for the linode. Must be [a-zA-Z0-9\-]*.
        type: string
        default: 'Cloudify-Linode'
      instance_type:
        description: >
          Instant Type by which Linodes are sized. Scales the amount of SSD, CPU, and data transfer provisioned, and effects the cost.
          Possible values at the moment are:
            [ g6-nanode-1, g6-standard-1, g6-standard-2, g6-standard-4, g6-standard-6, g6-standard-8, g6-standard-16, g6-standard-20, g6-standard-24, g6-standard-32, g6-highmem-1, g6-highmem-2, g6-highmem-4, g6-highmem-8, g6-highmem-16 ]
          An API call exists to retrieve all of these values.
        type: string
        default: 512mb
      # ip is inherited from cloudify.nodes.Compute
      #   All Linodes are associated to a publicly avail IPv4 address.
      # install_agent (boolean) is inherited from Compute
      # cloudify_agent {} is inherited from Compute
      region:
        description: >
          A magic slug for the Region where a Linode can be provisioned. The following are listed in the API at the time of writing:
            [us-central, us-west, us-southeast, us-east, eu-west, ap-south, eu-central, ap-northeast, ap-northeast-1a]
        type: string
        default: us-east
      private_network_enablement:
        type: boolean
        default: false
      ipv6_enablement:
        type: boolean
        default: false
      backup_enablement:
        type: boolean
        default: false
      image_slug:
        description: >
          A magic slug for the disk image (distribution).  At the time of writing, the available options are:
          [ linode/arch, linode/centos6.8, linode/centos7, linode/containerlinux, linode/debian8, linode/debian9, linode/fedora26, linode/fedora27, linode/fedora28, linode/fedora29, linode/gentoo, linode/opensuse15.0, linode/opensuse42.3, linode/slackware14.1, linode/slackware14.2, linode/ubuntu14.04lts, linode/ubuntu16.04lts, linode/ubuntu17.10, linode/ubuntu18.04, linode/ubuntu18.10 ]
        type: string
        default: linode/ubuntu18.04
      ssh_keys:
        description: >
          A list of ssh key locations, used for authentication.
        type: string
        default: []
      hostname:
        description: >
          An optional hostname.
        type: string
        default: ''
    interfaces:
      cloudify.interfaces.lifecycle:
        create: linode_plugin.create
        start: linode_plugin.start
        stop: linode_plugin.stop
